version: "3.9"
services:
  web:
    container_name: app
    restart: always
    build: .
    ports:
      - "9999:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"